// <auto-generated />
using System;
using MediasAsyncDemo.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MediasAsyncDemo.Migrations
{
    [DbContext(typeof(MediasContext))]
    partial class MediasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MediasAsyncDemo.Entities.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Name = "Shield Hero",
                            Type = "Series"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            Name = "Your Name",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = new Guid("24810dfc-2d94-4cc7-aab5-cdf98b83f0c9"),
                            Name = "Goblin Slayer",
                            Type = "Series"
                        },
                        new
                        {
                            Id = new Guid("2902b665-1190-4c70-9915-b9c2d7680450"),
                            Name = "Fairy Tail",
                            Type = "Series"
                        });
                });

            modelBuilder.Entity("MediasAsyncDemo.Entities.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ChannelId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("Medias");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5b1c2b4d-48c7-402a-80c3-cc796ad49c6b"),
                            ChannelId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Description = "While in the library, college student Naofumi Iwatani finds a fantasy book about \"Four Heroes\"; The Spear, Sword, Bow, and Shield.",
                            Title = "EP 1 The Shield Hero"
                        },
                        new
                        {
                            Id = new Guid("d8663e5e-7494-4f81-8739-6e0de1bea7ee"),
                            ChannelId = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            Description = "A teenage boy and girl embark on a quest to meet each other for the first time after they magically swap bodies.",
                            Title = "Your Name"
                        },
                        new
                        {
                            Id = new Guid("d173e20d-159e-4127-9ce9-b0ac2564ad97"),
                            ChannelId = new Guid("24810dfc-2d94-4cc7-aab5-cdf98b83f0c9"),
                            Description = "On Priestes first official adventure, she and her party of novices fall victim to murderous goblins.",
                            Title = "EP 1 The Fate of Particular Adventurers"
                        },
                        new
                        {
                            Id = new Guid("493c3228-3444-4a49-9cc0-e8532edc59b2"),
                            ChannelId = new Guid("2902b665-1190-4c70-9915-b9c2d7680450"),
                            Description = "When a phony wizard lures Lucy onto his ship with the promise of getting into the guild, her new friends must bail her out.",
                            Title = "EP 1 The Fairy Tail"
                        });
                });

            modelBuilder.Entity("MediasAsyncDemo.Entities.Media", b =>
                {
                    b.HasOne("MediasAsyncDemo.Entities.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
